# config for helix
# ~/.config/helix/config.toml
# In .bashrc :
# export HELIX_RUNTIME=~/helix/runtime
# For fish in ~/.config/fish/config.fish :
# nano ~/.config/fish/config.fish

theme = "onedark"

[editor]
line-number = "absolute"
mouse = true

[editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"

[editor.file-picker]
hidden = true


