# conf for lazygit ( .config/lazygit/config.yml )
os:
  editPreset: 'kakoune'
  edit: 'kakoune {{filename}}'
  editAtLine: 'kakoune --line={{line}} {{filename}}'
  editAtLineAndWait: 'kakoune --block --line={{line}} {{filename}}'
  editInTerminal: true
  openDirInEditor: 'kakoune {{dir}}'

# export EDITOR=kak
# export VISUAL=kak

customCommands:
 - key: O
   context: commits
   description: open files in commit
   command: git diff -z --name-only {{.SelectedLocalCommit.ParentRefName}} {{.SelectedLocalCommit.Sha}} | xargs -0 kak --
   subprocess: true
