# config for helix
# ~/.config/helix/config.toml

theme = "onedark"

[editor]
line-number = "absolute"
mouse = true
rainbow-brackets = true

[editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"

[editor.file-picker]
hidden = true

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]


