#!/usr/bin/env bash

# 1. Search for text in files using Ripgrep
# 2. Interactively restart Ripgrep with reload action
# 3. Open the file in Vim
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"
: | fzf-tmux --ansi --disabled --query "$INITIAL_QUERY" \
    --bind "start:reload:$RG_PREFIX {q}" \
    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
    --delimiter : \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
      --bind 'enter:become(echo "{1} {2}")'
      # --bind 'enter:become(echo "{1} {2}")'
    # --bind 'enter:become(vim {1} +{2})'
      # --bind 'enter:become(echo edit {1})'
      # --bind 'enter:become(echo "edit {1} +{2}" > $kak_command_fifo)'
      # --bind 'enter:become(echo eval -verbatim -try-client %val{client} edit "$0" | kak -p %val{session} {1} +{2})'

